/* eslint-disable */
/**
 * Generated API.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@0.12.2.
 * To regenerate, run `npx convex codegen`.
 * @module
 */

import type { ApiFromModules } from "convex/api";
import type * as queryVoters from "../queryVoters";
import type * as queryVotersByFirst from "../queryVotersByFirst";
import type * as saveVotersForEmail from "../saveVotersForEmail";

/**
 * A type describing your app's public Convex API.
 *
 * This `API` type includes information about the arguments and return
 * types of your app's query and mutation functions.
 *
 * This type should be used with type-parameterized classes like
 * `ConvexReactClient` to create app-specific types.
 */
export type API = ApiFromModules<{
  queryVoters: typeof queryVoters;
  queryVotersByFirst: typeof queryVotersByFirst;
  saveVotersForEmail: typeof saveVotersForEmail;
}>;
